spring:
    application:
        name: order-service
    data:
        redis:
            port: 6379
            host: localhost
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 0